name: Test CI

on:
  push:  # Runs on push to any branch
  pull_request:  # Runs on any PR

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile project
      run: make

    - name: Run Tests
      run: make test
